package bibo_dc

import "example.com/models:util"

#BIBODocumentClass:
	"bibo:AcademicArticle" |
	"bibo:Article" |
	"bibo:AudioDocument" |
	"bibo:AudioVisualDocument" |
	"bibo:Bill" |
	"bibo:Book" |
	"bibo:BookSection" |
	"bibo:Brief" |
	"bibo:Chapter" |
	"bibo:CollectedDocument" |
	"bibo:Document" |
	"bibo:DocumentPart" |
	"bibo:EditedBook" |
	"bibo:Email" |
	"bibo:Excerpt" |
	"bibo:Film" |
	"bibo:Image" |
	"bibo:Issue" |
	"bibo:LegalCaseDocument" |
	"bibo:LegalDecision" |
	"bibo:LegalDocument" |
	"bibo:Legislation" |
	"bibo:Letter" |
	"bibo:Manual" |
	"bibo:Manuscript" |
	"bibo:Map" |
	"bibo:Note" |
	"bibo:Patent" |
	"bibo:PersonalCommunicationDocument" |
	"bibo:Proceedings" |
	"bibo:Quote" |
	"bibo:ReferenceSource" |
	"bibo:Report" |
	"bibo:Slide" |
	"bibo:Slideshow" |
	"bibo:Specification" |
	"bibo:Standard" |
	"bibo:Statute" |
	"bibo:Thesis" |
	"bibo:Webpage"

#AdditionalBIBOInformation: {
	"bibo:abstract"?: util.#JSONValue
	"bibo:affirmedBy"?: util.#JSONValue
	"bibo:annotates"?: util.#JSONValue
	"bibo:argued"?: util.#JSONValue
	"bibo:asin"?: util.#JSONValue
	"bibo:chapter"?: util.#JSONValue
	"bibo:citedBy"?: util.#JSONValue
	"bibo:cites"?: util.#JSONValue
	"bibo:coden"?: util.#JSONValue
	"bibo:contributorList"?: util.#JSONValue
	"bibo:court"?: util.#JSONValue
	"bibo:degree"?: util.#JSONValue
	"bibo:director"?: util.#JSONValue
	"bibo:distributor"?: util.#JSONValue
	"bibo:doi"?: util.#JSONValue
	"bibo:eanucc13"?: util.#JSONValue
	"bibo:edition"?: util.#JSONValue
	"bibo:editor"?: util.#JSONValue
	"bibo:editorList"?: util.#JSONValue
	"bibo:eissn"?: util.#JSONValue
	"bibo:gtin14"?: util.#JSONValue
	"bibo:handle"?: util.#JSONValue
	"bibo:identifier"?: util.#JSONValue
	"bibo:interviewee"?: util.#JSONValue
	"bibo:interviewer"?: util.#JSONValue
	"bibo:isbn"?: util.#JSONValue
	"bibo:isbn10"?: util.#JSONValue
	"bibo:isbn13"?: util.#JSONValue
	"bibo:issn"?: util.#JSONValue
	"bibo:issue"?: util.#JSONValue
	"bibo:issuer"?: util.#JSONValue
	"bibo:lccn"?: util.#JSONValue
	"bibo:locator"?: util.#JSONValue
	"bibo:numPages"?: util.#JSONValue
	"bibo:numVolumes"?: util.#JSONValue
	"bibo:number"?: util.#JSONValue
	"bibo:oclcnum"?: util.#JSONValue
	"bibo:organizer"?: util.#JSONValue
	"bibo:owner"?: util.#JSONValue
	"bibo:pageEnd"?: util.#JSONValue
	"bibo:pageStart"?: util.#JSONValue
	"bibo:pages"?: util.#JSONValue
	"bibo:performer"?: util.#JSONValue
	"bibo:pmid"?: util.#JSONValue
	"bibo:prefixName"?: util.#JSONValue
	"bibo:presentedAt"?: util.#JSONValue
	"bibo:presents"?: util.#JSONValue
	"bibo:producer"?: util.#JSONValue
	"bibo:recipient"?: util.#JSONValue
	"bibo:reproducedIn"?: util.#JSONValue
	"bibo:reversedBy"?: util.#JSONValue
	"bibo:reviewOf"?: util.#JSONValue
	"bibo:section"?: util.#JSONValue
	"bibo:shortDescription"?: util.#JSONValue
	"bibo:shortTitle"?: util.#JSONValue
	"bibo:sici"?: util.#JSONValue
	"bibo:status"?: util.#JSONValue
	"bibo:subsequentLegalDecision"?: util.#JSONValue
	"bibo:suffixName"?: util.#JSONValue
	"bibo:transcriptOf"?: util.#JSONValue
	"bibo:translationOf"?: util.#JSONValue
	"bibo:translator"?: util.#JSONValue
	"bibo:upc"?: util.#JSONValue
	"bibo:uri"?: util.#JSONValue
	"bibo:volume"?: util.#JSONValue
}

#AdditionalDublinCoreInformation: {
	"dcterms:abstract"?: util.#JSONValue
	"dcterms:accessRights"?: util.#JSONValue
	"dcterms:accrualMethod"?: util.#JSONValue
	"dcterms:accrualPeriodicity"?: util.#JSONValue
	"dcterms:accrualPolicy"?: util.#JSONValue
	"dcterms:alternative"?: util.#JSONValue
	"dcterms:audience"?: util.#JSONValue
	"dcterms:available"?: util.#JSONValue
	"dcterms:bibliographicCitation"?: util.#JSONValue
	"dcterms:conformsTo"?: util.#JSONValue
	"dcterms:contributor"?: util.#JSONValue
	"dcterms:coverage"?: util.#JSONValue
	"dcterms:created"?: util.#JSONValue
	"dcterms:creator"?: util.#JSONValue
	"dcterms:date"?: util.#JSONValue
	"dcterms:dateAccepted"?: util.#JSONValue
	"dcterms:dateCopyrighted"?: util.#JSONValue
	"dcterms:dateSubmitted"?: util.#JSONValue
	"dcterms:description"?: util.#JSONValue
	"dcterms:educationLevel"?: util.#JSONValue
	"dcterms:extent"?: util.#JSONValue
	"dcterms:format"?: util.#JSONValue
	"dcterms:hasFormat"?: util.#JSONValue
	"dcterms:hasPart"?: util.#JSONValue
	"dcterms:hasVersion"?: util.#JSONValue
	"dcterms:identifier"?: util.#JSONValue
	"dcterms:instructionalMethod"?: util.#JSONValue
	"dcterms:isFormatOf"?: util.#JSONValue
	"dcterms:isPartOf"?: util.#JSONValue
	"dcterms:isReferencedBy"?: util.#JSONValue
	"dcterms:isReplacedBy"?: util.#JSONValue
	"dcterms:isRequiredBy"?: util.#JSONValue
	"dcterms:isVersionOf"?: util.#JSONValue
	"dcterms:language"?: util.#JSONValue
	"dcterms:license"?: util.#JSONValue
	"dcterms:mediator"?: util.#JSONValue
	"dcterms:medium"?: util.#JSONValue
	"dcterms:modified"?: util.#JSONValue
	"dcterms:provenance"?: util.#JSONValue
	"dcterms:publisher"?: util.#JSONValue
	"dcterms:references"?: util.#JSONValue
	"dcterms:relation"?: util.#JSONValue
	"dcterms:replaces"?: util.#JSONValue
	"dcterms:requires"?: util.#JSONValue
	"dcterms:rights"?: util.#JSONValue
	"dcterms:rightsHolder"?: util.#JSONValue
	"dcterms:source"?: util.#JSONValue
	"dcterms:spatial"?: util.#JSONValue
	"dcterms:subject"?: util.#JSONValue
	"dcterms:tableOfContents"?: util.#JSONValue
	"dcterms:temporal"?: util.#JSONValue
	"dcterms:type"?: util.#JSONValue
	"dcterms:valid"?: util.#JSONValue
}

#AdditionalSourceInformation:
	#AdditionalBIBOInformation &
	#AdditionalDublinCoreInformation
